paddles: Adding a queueing mechanism to Paddles
ceph/paddles pull request #94
Opened 2021-05-14 07:03 UTC by amathuria

This change adds support for a queuing mechanism in Paddles. The idea is to eventually use only the Paddles backend for teuthology and remove the need for the Beanstalk queue

The following are the changes made:
1. Addition of new fields to the Jobs table in order to store the entire teuthology config.
2. Addition of a priority field to mimic a priority queue (similar to Beanstalk)
3. A new Queue table to keep track of the queues and their statuses on various machine types
4. Generation of a unique Job ID in Paddles
5. Rest APIs for retrieving a job from the queue, creating a new queue, updating status of a queue and  retrieving stats for a particular queue

Signed-off-by: Aishwarya Mathuria <amathuri@redhat.com>

2021-05-17 02:41 UTC, jdurgin reviewed
This is looking good! IIRC you had some alembic changes to the fields as well - looks like they weren't added in this commit.

It'd be great to add some unit tests for the new/updated models and controllers, particularly ones with logic - e.g. for updating job priority it looks like you had to modify the model to work without targets, and only an update of priority

2021-05-17 02:41 UTC, jdurgin commented on paddles/models/queue.py
> +                        "Cannot {verb} an already-{verb}ed node".format(
you can use python3 f-strings to simplify this and other format strings - e.g. this is equivalent to ```f"Cannot {verb} an already-{verb}ed node"```

2021-05-17 02:41 UTC, jdurgin commented on paddles/models/queue.py
> +            elif (verb == 'unpause' and was_paused and to_pause_for !=
this is a new constraint, but I think it's a good idea to avoid confusion - could include the current paused_by in the error message as well

2021-05-17 02:41 UTC, jdurgin commented on paddles/controllers/queue.py
> +                paused=pause_duration,
should this be comparing the current time to paused_since + pause_duration?

2021-05-17 13:21 UTC, amathuria commented on paddles/models/queue.py
> +            elif (verb == 'unpause' and was_paused and to_pause_for !=
Sure

2021-05-17 13:51 UTC, amathuria commented on paddles/controllers/queue.py
> +                paused=pause_duration,
Oh you mean it should return how much longer the queue will be paused?

2021-05-17 14:51 UTC, jdurgin commented on paddles/controllers/queue.py
> +                paused=pause_duration,
I was thinking the intent was returning whether the queue was currently paused or not, which seems fine, but perhaps I was interpreting pause_duration differently from your intent

2021-05-19 16:14 UTC, jdurgin commented on paddles/controllers/queue.py
> +            rollback()
is the explicit rollback required? if so we might need to add it a lot of other places

2021-05-20 14:34 UTC, amathuria commented on paddles/controllers/queue.py
> +            rollback()
An explicit rollback will not be needed. I will remove these.

2021-05-20 14:41 UTC, amathuria commented on paddles/controllers/queue.py
> +            rollback()
There is an explicit rollback here as well: https://github.com/ceph/paddles/blob/master/paddles/controllers/nodes.py#L52. 
I'll test if it is required for a ValueError and update accordingly

2021-05-20 14:51 UTC, kshtsk commented
travis tests are failing, btw

2021-05-20 14:59 UTC, kshtsk commented on paddles/controllers/queue.py
> +            error('/errors/invalid/', "could not find required keys: 'machine_type' and 'user'")
This error message can misguide a user, for usability it would be better to have a separate message per key.

2021-05-20 15:05 UTC, kshtsk commented on paddles/models/jobs.py
> +    openstack = Column(JSONType())
what is this needed for?

2021-05-25 18:56 UTC, amathuria commented on paddles/controllers/queue.py
> +            error('/errors/invalid/', "could not find required keys: 'machine_type' and 'user'")
Sure I'll change that

2021-05-25 19:01 UTC, amathuria commented
> travis tests are failing, btw

@kshtsk I can see a connection refused error in the test logs here: https://travis-ci.org/github/ceph/paddles/builds/771656065#L711. Any idea how I can fix this?

2021-06-03 13:25 UTC, amathuria commented on paddles/models/jobs.py
> +    openstack = Column(JSONType())
This is for storing the openstack blob in the teuthology job configuration. It looks something like this: 

`openstack:
  - volumes:
      count: 4
      size: 10`

2021-06-03 13:26 UTC, amathuria commented on paddles/controllers/queue.py
> +            rollback()
The explicit rollback is not required. I will remove it

2021-06-07 07:31 UTC, jdurgin commented
could you add a unit test for updating job priority? the new queue tests look good.

For the travis failure, do the same commands work for you locally? i.e. the commands starting here https://travis-ci.com/github/ceph/paddles/builds/227874146#L196

Though travis doesn't show the paddles log, it looks like paddles is crashing quickly after startup

2021-06-07 08:01 UTC, kshtsk commented
> > travis tests are failing, btw
> 
> @kshtsk I can see a connection refused error in the test logs here: https://travis-ci.org/github/ceph/paddles/builds/771656065#L711. Any idea how I can fix this?

This means that server is not started in fact, you must try reproduce it on your local machine.

2021-06-09 14:02 UTC, kshtsk commented
```E           TypeError: Invalid argument(s) 'listeners' sent to create_engine(), using configuration SQLiteDialect_pysqlite/NullPool/Engine.  Please check that the keyword arguments are appropriate for this combination of components.
```

2021-06-09 14:03 UTC, kshtsk commented
```
paddles/models/__init__.py:124:1: F401 '.queue.Queue' imported but unused
paddles/models/queue.py:1:1: F401 'sqlalchemy.exc' imported but unused
```

2021-06-09 14:10 UTC, amathuria commented
> > > travis tests are failing, btw
> > 
> > 
> > @kshtsk I can see a connection refused error in the test logs here: https://travis-ci.org/github/ceph/paddles/builds/771656065#L711. Any idea how I can fix this?
> 
> This means that server is not started in fact, you must try reproduce it on your local machine.

Sure I will do that.

2021-06-09 14:11 UTC, kshtsk commented
```
> docker run --name=xxxx -d -p 80:8080 -e PADDLES_SERVER_HOST=0.0.0.0 -e PADDLES_SQLALCHEMY_URL=sqlite:///dev.db ceph-paddles-test
9215e5fe3b5bb24e433b6ac2586df37523fcae114497b2495fccfb1c20615949
> docker logs xxxx
==> LOADING ENVIRONMENT
Traceback (most recent call last):
  File "/usr/local/bin/pecan", line 11, in <module>
    sys.exit(CommandRunner.handle_command_line())
  File "/usr/local/lib/python3.6/dist-packages/pecan/commands/base.py", line 96, in handle_command_line
    runner.run(sys.argv[1:])
  File "/usr/local/lib/python3.6/dist-packages/pecan/commands/base.py", line 91, in run
    self.commands[ns.command_name]().run(ns)
  File "/usr/local/lib/python3.6/dist-packages/paddles/commands/populate.py", line 20, in run
    self.load_app()
  File "/usr/local/lib/python3.6/dist-packages/pecan/commands/base.py", line 162, in load_app
    return load_app(self.args.config_file)
  File "/usr/local/lib/python3.6/dist-packages/pecan/core.py", line 218, in load_app
    app = module.app.setup_app(_runtime_conf, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/paddles/app.py", line 7, in setup_app
    models.init_model()
  File "/usr/local/lib/python3.6/dist-packages/paddles/models/__init__.py", line 74, in init_model
    conf.sqlalchemy.engine = _engine_from_config(conf.sqlalchemy)
  File "/usr/local/lib/python3.6/dist-packages/paddles/models/__init__.py", line 86, in _engine_from_config
    return create_engine(url, **configuration)
  File "<string>", line 2, in create_engine
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/deprecations.py", line 298, in warned
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/create.py", line 645, in create_engine
    engineclass.__name__,
TypeError: Invalid argument(s) 'listeners' sent to create_engine(), using configuration SQLiteDialect_pysqlite/NullPool/Engine.  Please check that the keyword arguments are appropriate for this combination of components.

```

2021-06-09 14:12 UTC, kshtsk commented
@amathuria usually you must make the PR run without unittests failures first ;-)

2021-06-09 14:28 UTC, kshtsk commented on paddles/controllers/queue.py
> +            error('/errors/invalid/', "'user' key or 'run_name' key is required")
This is all not super user friendly. Maybe try and accumulate all the missing keys and report them at once?
```
required_keys = ('machine_type', 'user', 'run_name')
missing_keys = [_ for _ in required_keys if _ not in data]
if missing_keys:
    error('/errors/invalid/', f"could not find required key: {missing_keys}")
```

2021-06-09 14:38 UTC, amathuria commented on paddles/controllers/queue.py
> +            error('/errors/invalid/', "'user' key or 'run_name' key is required")
The problem I was facing is that the 'user' and 'run_name' key are not required but we do require at least one of them to filter the jobs and return them. 
I made the change for the following review comment: https://github.com/ceph/teuthology/pull/1650#discussion_r646324897.

2021-06-09 14:42 UTC, amathuria commented
> @amathuria usually you must make the PR run without unittests failures first ;-)

Thank you for the logs. I was testing my changes on a mira setup with postgres and tested the postgres library upgrade there (which is causing the issue here in the docker test) and not with sqlite. I'm working on the fix.

2021-06-09 15:05 UTC, kshtsk commented on paddles/controllers/queue.py
> +            error('/errors/invalid/', "'user' key or 'run_name' key is required")
Hm.... I see... but in general why would we restrict API to only those two use cases, for example, it would be useful to get the full queue, not only restricted by user or run?

2021-06-10 12:30 UTC, amathuria commented on paddles/controllers/queue.py
> +            error('/errors/invalid/', "'user' key or 'run_name' key is required")
Ah I get what you're saying. It does seem cleaner to just return the entire queue. However on teuthology side this could be a lot of jobs to filter through each time?
I restricted it to only 'user' or 'run' here because they are the ones used for teuthology-queue operations such as listing all runs for a user or changing priority of all jobs in a run.

2021-07-19 14:12 UTC, jdurgin commented
![](https://github.trello.services/images/mini-trello-icon.png) [replace beanstalk queue](https://trello.com/c/wi9oBMZ6/343-replace-beanstalk-queue)

2021-07-22 21:05 UTC, jdurgin commented on alembic/versions/e8de4928657_modify_jobs_table.py
> +Revises: 4699efaaee99
this migration doesn't quite work from scratch - it does with these changes: 
```
diff --git a/alembic/versions/e8de4928657_modify_jobs_table.py b/alembic/versions/e8de4928657_modify_jobs_table.py
index e0e5848..6c1be05 100644
--- a/alembic/versions/e8de4928657_modify_jobs_table.py
+++ b/alembic/versions/e8de4928657_modify_jobs_table.py
@@ -1,14 +1,14 @@
 """modify jobs table
 
 Revision ID: e8de4928657
-Revises: 4699efaaee99
+Revises: 11e2594da07b
 Create Date: 2021-06-28 13:45:32.717585
 
 """
 
 # revision identifiers, used by Alembic.
 revision = 'e8de4928657'
-down_revision = '4699efaaee99'
+down_revision = '11e2594da07b'
 
 from alembic import op
 from paddles.models.types import JSONType
@@ -30,7 +30,6 @@ def upgrade():
     op.add_column(u'jobs', sa.Column('user', sa.String(length=64), nullable=True))
     op.create_index(op.f('ix_jobs_job_id'), 'jobs', ['job_id'], unique=False)
     op.create_index(op.f('ix_jobs_teuthology_sha1'), 'jobs', ['teuthology_sha1'], unique=False)
-    op.drop_index('ix_jobs_archive_path', table_name='jobs')
 
 
 def downgrade():
```

2021-07-27 09:07 UTC, amathuria commented on alembic/versions/e8de4928657_modify_jobs_table.py
> +Revises: 4699efaaee99
Made the changes, thank you!

2021-08-16 07:08 UTC, kshtsk commented on paddles/models/jobs.py
> +    first_in_suite = Column(Boolean())
This item should be discussed, if really want to improve the queueing process, why do we need first_in_suite and last_in_suite field? It is possible to check how many jobs are still in progress just querying the db.

2021-08-16 07:17 UTC, kshtsk commented on paddles/models/jobs.py
> +    teuthology_branch = Column(String(64))
The sha1 which is used in git is 160-bit, which is 160/4(bits per hex) = 40 (hex symbols)

2021-08-16 14:29 UTC, jdurgin commented on paddles/models/jobs.py
> +    teuthology_branch = Column(String(64))
this is the branch name, the sha1 is a separate field

2021-08-16 14:30 UTC, jdurgin commented on paddles/models/jobs.py
> +    first_in_suite = Column(Boolean())
good point, I don't see a reason to keep them around as fields per se, the dispatcher just needs to know when it's handling the first/last job in a run

2021-08-16 15:38 UTC, kshtsk commented on paddles/models/jobs.py
> +    teuthology_branch = Column(String(64))
Oops... wrong line

2021-11-02 19:59 UTC, zmc requested changes
There's a lot of good work here! I don't think this is too far from being ready.

I've left a lot of comments, and tried to be clear, but if you have any questions, or if I just got something wrong, let me know.

2021-11-02 19:59 UTC, zmc commented on paddles/controllers/queue.py
> +        job = job_query.order_by(Job.priority).first()
If the queue's empty, this looks like we'll throw a 500

2021-11-02 19:59 UTC, zmc commented on paddles/controllers/queue.py
> +        job = job_query.order_by(Job.priority).first()
Also, there's no mention of whether or not the queue is paused.

2021-11-02 19:59 UTC, zmc commented on paddles/controllers/queue.py
> +            pause_duration = Session.query(Queue.pause_duration).filter(Queue.machine_type==machine_type).first()[0]
This query doesn't look quite right for me, and `pause_duration` doesn't seem to be covered by unit tests. Shouldn't it look more like `Queue.query(Queue.machine_type==machine_type).first()[0].pause_duration` ?

2021-11-02 19:59 UTC, zmc commented on paddles/controllers/queue.py
> +                paused=pause_duration,
I agree that this is confusing and possibly incorrect. I could always be missing something, but I'm concerned that pausing isn't properly implemented. I'll try to illustrate:

1. At 00:00:00 I pause the queue for 60s
1. At 00:00:01 I `GET /queue/stats`
1. I get the response `{...paused: 60}`
1. At 00:00:59 I `GET /queue/stats`
1. I get the same response `{...paused: 60}`; worse, if the request is a bit slow the queue will _already_ be unpaused

Additionally, the queue doesn't seem to really have a way to actually unpause itself. We can only commit to the database during `PUT/POST/DELETE` ops, so `GETting /queue/pop_queue` won't work.

I'd propose something a little different:

* Drop `Queue.paused` and `Queue.pause_duration` in favor of `paused_until`
* Create a `property` called `Queue.paused` that returns `True/False` based on the value of `paused_until` relative to the current time


When we are queried for the queue status, we can respond with:
* If `paused == False`: just `paused`
* If `paused == True`: `paused, paused_since, paused_until, paused_by`

And, we only need to `commit()` during pause/unpause operations, _not_ when the pause expires normally.

2021-11-02 19:59 UTC, zmc commented on paddles/controllers/queue.py
> +            error('/errors/invalid/', "'user' key or 'run_name' key is required")
We need to be able to return the entire queue from this endpoint. We could make `user`, `run_name` etc. query params instead of requiring the user to `GET` with a JSON payload.

2021-11-02 19:59 UTC, zmc commented on paddles/controllers/jobs.py
> +                '''
Just `# comment like this please` 🙂

2021-11-02 19:59 UTC, zmc commented on paddles/controllers/jobs.py
> +            log.info("Job ID: %s", job_id)
This should just be part of the next log message

2021-11-02 19:59 UTC, zmc commented on paddles/controllers/jobs.py
> +            log.info(data)
I don't think we should log entire job objects at any point and especially not above the debug level

2021-11-02 19:59 UTC, zmc commented on paddles/controllers/queue.py
> +        job_query = Job.filter_by(status='queued').filter_by(machine_type=machine_type)
What about multiple-machine-type jobs?

2021-11-02 19:59 UTC, zmc commented on paddles/controllers/root.py
> +
Drop the extra newlines please

2021-11-03 12:35 UTC, amathuria commented on paddles/controllers/jobs.py
> +                '''
Sure will do.

2021-11-08 10:20 UTC, amathuria commented on paddles/controllers/queue.py
> +                paused=pause_duration,
Yeah this sounds less complicated to me. I'll make the change.

2021-11-12 14:24 UTC, amathuria commented on paddles/controllers/queue.py
> +        job_query = Job.filter_by(status='queued').filter_by(machine_type=machine_type)
This will be handled on the teuthology side.
We create a paddles queue for each unique machine type we see in the job configurations (https://github.com/ceph/teuthology/pull/1650/files#diff-1540ecbee64b0c54b3e20e5210435b313a9c424546c1528f68b83a92ce67ab08R97), the dispatcher gets the job by calling this function with the appropriate machine_type (https://github.com/ceph/teuthology/pull/1650/files#diff-518b3a856fe844adcc19187dade87bd07738e36d20a528eef4834be57b0ba4d0R129). 
You can have a look and let me know if this makes sense?

2021-11-12 23:02 UTC, zmc commented on paddles/controllers/queue.py
> +        job_query = Job.filter_by(status='queued').filter_by(machine_type=machine_type)
I realized I needed to refresh my memory on this, so I read through `teuthology.suite` and `teuthology.schedule` code. 


1. `suite` passes `--worker` to `teuthology-schedule`. Usually this is the same value as `machine_type`, but for multiple-machine-type jobs, it is always `multi` (meanwhile the `machine_type` would be e.g. "smithi,gibba").
2. `teuthology-schedule` internally uses the `--worker` value as the beanstalk `tube` to use when submitting jobs
3. If a `multi` dispatcher is running, it will monitor the `multi` tube for jobs to run (In sepia, we do not currently have a `multi` dispatcher)

So I think we should preserve that behavior with paddles. As far as creating queues goes, it does look to me like we'd be trying to create the queue for each job scheduled; that'll slow down the scheduling process quite a bit, I'd think, since the queues will only ever needed to be created once. We could do it once _per run_, or... maybe teuthology just assumes the queues already exist - and if they don't, the user may have made a mistake.

2021-11-18 00:56 UTC, zmc commented on paddles/controllers/queue.py
> +        job_query = Job.filter_by(status='queued').filter_by(machine_type=machine_type)
I want to try to be more clear about what preserving the existing behavior means. It's easier than it sounds, I think.

Beanstalk, being a generic queue, has no knowledge of the purpose or contents of a queue. Likewise, paddles does not need to know what we use a given queue for. 

At schedule time, teuthology will decide which queue to place a job in based on the `machine_type` value. The decision is simple: If the value contains a comma, it is a multi-machine-type job and goes to the `multi` queue. If not, `queue = machine_type`. Teuthology already has this logic.

With beanstalk, which calls its queues 'tubes', we store that value as `job_config['tube']`; with paddles, I believe we simply need to add a `queue` column to the schema, populate that via teuthology, and keep in mind that `queue` and `machine_type` are not interchangeable.

At run time, the job has already been popped off the queue - if it's a `multi` job, then teuthology takes the `machine_type` value, splits it by the `,`, and does a `lock_many` request for each individual `machine_type` until it has enough nodes.

2021-11-18 09:07 UTC, amathuria commented on paddles/controllers/queue.py
> +        job_query = Job.filter_by(status='queued').filter_by(machine_type=machine_type)
Okay that clears up things for me. So just to double check: 
1. We add a `queue` column to the Job schema
2. The `multi` queue is created in Paddles when there are multiple machine types in the job config (similar to the current beanstalk workflow)

2021-11-18 22:22 UTC, kshtsk commented on paddles/controllers/queue.py
> +        job_query = Job.filter_by(status='queued').filter_by(machine_type=machine_type)
I am a bit skeptical about adding a queue to Job schema, for generalisation it is better to not bind job to the machine_type at all, since in general we want to be about to run a test case on multiple architectures for example.

2021-11-22 14:49 UTC, amathuria commented on paddles/controllers/queue.py
> +        job_query = Job.filter_by(status='queued').filter_by(machine_type=machine_type)
@kshtsk I don't think I understood this. By machine_type we mean the test machine right? (smithi, mira, etc) And not the architecture?

2023-08-07 19:06 UTC, zmc commented
@amathuria I think you mentioned you'd rebased this - could you re-push please? Thanks!

2023-10-12 02:48 UTC, amathuria commented on paddles/controllers/queue.py
> +        job = job_query.order_by(Job.priority).first()
I have added the check for paused queue. I'll add in one for when the queue is empty as well.

2023-10-16 11:44 UTC, amathuria commented on paddles/models/jobs.py
> +        self.id = json_data['id']
Yeah you are right, just tested it out and this won't be needed.  I wanted to keep id in sync with job_id but there is a better way of doing that.

2024-02-14 00:25 UTC, zmc commented on paddles/tests/controllers/test_nodes.py
> +        assert result[2]['job_id'] == response_job_ids[0]
The above is effectively doing:
`assert response.json[0]['job_id'] == response.json[0]['job_id']`
isn't it?

2024-02-14 00:25 UTC, zmc commented on alembic/versions/e8de4928657_modify_jobs_table.py
> +    op.add_column(u'jobs', sa.Column('openstack', JSONType(), nullable=True))
There was some discussion around whether we need or want `openstack`, `first_in_suite` and `last_in_suite`; I notice we don't have `last_in_suite` in this migration as well.

We can talk about this 1:1, but I'm thinking it might make sense to remove these from this PR, and before merging the teuthology PR, update it to query paddles when it needs to know if any or all of a suite's jobs have been run.

2024-02-28 02:32 UTC, amathuria commented on paddles/tests/controllers/test_nodes.py
> +        assert result[2]['job_id'] == response_job_ids[0]
Ah yes, I'll fix this.

2024-02-28 16:06 UTC, amathuria commented on paddles/tests/controllers/test_nodes.py
> +        assert result[2]['job_id'] == response_job_ids[0]
@zmc sorry my bad, it's creating jobs on a single node (t1)  and then querying /nodes/jobs/ to see if the jobs are returned. Does that make sense?

2024-03-04 23:07 UTC, zmc approved these changes

2024-03-04 23:21 UTC, merged